### ISSUE TITLE
Fire Animals - CNAME and CTA Request

### ISSUE THREAD

**Issue by calebhaye** [chimera/sonomafireinfo.com#3]
Hi Team,

I've put together an app that repurposes some code I imagined and then worked on with other developers for the Valley Fire.  It's a resource that was well received during the Valley Fire, and I think could go a long way now that Sonoma County is in need.

This request is for 2 things:
1) A CNAME DNS Record for animals.sonomafireinfo.com pointed to sonomafireanimals.continuousintegrations.com
2) A Call to Action / Button on the homepage that links to the new resource, perhaps titled "Animal Lost & Found"

Beyond that, any help spreading the word by reaching out directly to vets and shelters would be appreciated and helpful.

You can check out the site at http://sonomafireanimals.continuousintegrations.com, and of course, any feedback is welcomed.

**Comment by calebhaye** [comment]
FYI - PR here for button https://github.com/chimera/sonomafireinfo.com/pull/4

**Comment by manguluka** [comment]
Seems to be a misspelling in original comment, site is up at: http://sonomafireanimals.continuousintegrations.com

**Comment by calebhaye** [comment]
@manguluka site is up at animals.sonomafireinfo.com as well
